trigger: 
-  master 
pool: winvm 
stages: 
- stage: Build 
  jobs: 
  # - job: 
  #   steps: 
  #   # - script: "CI BUILD"  
steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions